### ISSUE TITLE
supporting parse simple chinese in Class Message[Read, Content]

### ISSUE THREAD

**Issue by Evilmass** [Miksus/red-box#10]
```python
def get_unread_mail():
    box = EmailBox(
        host="imap.gmail.com",
        port="993",
        username="",
        password="",
    )
    msgs = box["INBOX"].search(unseen=True)
    # msgs [0].subject
    msg.unread()
```

when simple chinese text in msgs [0].subject, it return:
```shell
Subject: =?UTF-8?Q?Re:_[Bug]:?==?UTF-8?Q?_=E
```

**Comment by solanav** [comment]
Hi! I fixed this on my fork [`solanav/red-box`](https://github.com/solanav/red-box) just in case you still need it. You can install my fork with `pip install redbox2`.

**Comment by Evilmass** [comment]
> Hi! I fixed this on my fork [`solanav/red-box`](https://github.com/solanav/red-box) just in case you still need it. You can install my fork with `pip install redbox2`.

THX!
